Add/rainsensor
sensebox/node-sketch-templater pull request #139
Opened 2023-08-17 10:11 UTC by Thiemann96

2023-09-11 08:13 UTC, mpfeil requested changes
@Thiemann96 could you also add the sensor to the `ethernet` & `lora` templates

2023-09-13 08:12 UTC, Thiemann96 commented
I added ethernet and lora sketch. I had to add some transformers to the ttn integration which can be seen here https://github.com/sensebox/ttn-osem-integration/pull/51

I cant test that right now, so some feedback would be appreciated

2023-09-14 06:18 UTC, mpfeil commented
@mariopesch @PaulReichmuth could you test the different sketches and provide some feedback please.

2025-03-14 15:10 UTC, BjoernLuig commented
- added rainsensor and solar charger (with rescaling to uint in lora sketch -> TODO for opensensemap)
- included compiler error messages in test script
- moved sds sensor into normal (not "feinstaub") scripts -> TODO for opensensemap, no feinstaub model needed in homev2
- changed  "serialPort" to "sdsSerialPort" and "rg15SerialPort" -> TODO for opensensmap
- commented out SPS30 because it was only implemented in the wifi template and should not be part of sensebox home
- testet all changes in docker container

@eric can you check it?

2025-03-17 10:34 UTC, Thiemann96 commented on Dockerfile
> -RUN arduino-cli lib install --zip-path sps30.zip
why would we delete that?

2025-03-17 10:34 UTC, Thiemann96 commented on templates/homev2_wifi.tpl
> +//  uint32_t auto_clean;
please dont leave commented code in the template. use it or remove it

2025-03-17 10:34 UTC, Thiemann96 commented on templates/homev2_wifi.tpl
> +  // #endif
same as above

2025-03-17 10:34 UTC, Thiemann96 commented on templates/homev2_wifi.tpl
> +  // #endif
.

2025-03-17 14:29 UTC, merged